# Generated by Django 2.2 on 2019-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='studentDoubleMajor',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='studentTrack',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
