# Generated by Django 2.2 on 2019-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradebyperiod',
            name='gradeByPeriodName',
            field=models.CharField(max_length=20),
        ),
    ]
