# Generated by Django 2.2 on 2019-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190513_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ForTableUserName', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=10)),
                ('lectureName', models.CharField(max_length=40)),
                ('lectureNumber', models.CharField(max_length=10)),
                ('lecturePoint', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
