# Generated by Django 2.2 on 2019-05-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190508_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='studentSubMajor',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
