# Generated by Django 2.2 on 2019-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takelist',
            name='lecturePoint',
            field=models.FloatField(default=0),
        ),
    ]
