# Generated by Django 2.2 on 2019-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_studentconvergencemajor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='studentTeaching',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
