# Generated by Django 2.2 on 2019-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190512_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='takelist',
            name='addedCustom',
            field=models.BooleanField(default=False),
        ),
    ]
