# Generated by Django 2.2 on 2019-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduYear', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('lectureName', models.CharField(max_length=20)),
                ('lectureNum', models.CharField(max_length=10)),
                ('lecturePoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduYear', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('lectureName', models.CharField(max_length=20)),
                ('lectureNum', models.CharField(max_length=10)),
                ('lecturePoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20)),
                ('lectureName', models.CharField(max_length=20)),
                ('lectureNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PioneerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduYear', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('lectureName', models.CharField(max_length=20)),
                ('lectureNum', models.CharField(max_length=10)),
                ('lecturePoint', models.IntegerField()),
            ],
        ),
    ]
