# Generated by Django 2.2 on 2019-05-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0002_major'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major',
            new_name='MajorPoint',
        ),
    ]
