# Generated by Django 2.2 on 2019-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_auto_20190508_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduYear', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('seperate', models.CharField(max_length=20)),
                ('dmajorName', models.CharField(max_length=20)),
                ('dmajornum', models.CharField(max_length=20)),
                ('dmajorPoint', models.FloatField()),
            ],
        ),
    ]
