# Generated by Django 2.2 on 2019-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0004_convergencemajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=10)),
                ('lectureNum', models.CharField(max_length=10)),
                ('lectureName', models.CharField(max_length=20)),
                ('lecturePoint', models.IntegerField()),
                ('checkSubMajor', models.IntegerField(default=0)),
                ('checkDoubleMajor', models.IntegerField(default=0)),
            ],
        ),
    ]
