# Generated by Django 2.2 on 2019-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0007_edubasic_educareer_eduteach'),
    ]

    operations = [
        migrations.AddField(
            model_name='edubasic',
            name='eduYear',
            field=models.IntegerField(default=1),
        ),
    ]
