# Generated by Django 2.2 on 2019-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0008_edubasic_eduyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10)),
                ('lectureNumber', models.CharField(max_length=10)),
                ('lectureName', models.CharField(max_length=40)),
                ('lecturePoint', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
